### ISSUE TITLE
if file system is full, shutting down bot empties config file

### ISSUE THREAD

**Issue by puphime** [Chronister/ananas#13]
see above, thankfully i had a copy of it elsewhere

**Comment by fwenzel** [comment]
Full filesystem will mess up your system in many ways. In this case, ananas tries to write the config file but the system won't let it; there's very little that can be done.

**Comment by chr-1x** [comment]
Just pushed to master and to pypi a fix for this. Basically what we can do is try to write to a tempfile, then replace the user config with that if it succeeds. That way if the fs is full the write to the tempfile will fail first without touching the user config.

**Comment by ashkitten** [comment]
Does this fix work properly if the tempfile is on a different filesystem, like tmpfs?

**Comment by chr-1x** [comment]
It should, since the call to replace should fail, but: yes, as a precaution I think it makes sense to write the provisional config update to the same folder as the user config file.

**Comment by chr-1x** [comment]
Fixed in 0cc76e71c97f458437ae74a93b74c2b8e61bb343
