### ISSUE TITLE
Extra backslashes in readme.md

### ISSUE THREAD

**Issue by fwenzel** [Chronister/ananas#24]
Probably not a big deal:

![image](https://user-images.githubusercontent.com/87232/77602286-4b0fd780-6eca-11ea-82fc-0648c2c19cea.png)

**Comment by chr-1x** [comment]
Ah, markdown. Consistently inconsistent across different implementations :roll_eyes: Fixed in 12c47e1ef4a03ef00c6a7c11ece1f13fc71cca21
