### ISSUE TITLE
v1.0.0b18 changes missing from repo

### ISSUE THREAD

**Issue by codl** [Chronister/ananas#26]
looks like this repo is one release behind pypi

**Comment by chr-1x** [comment]
oh damb

**Comment by chr-1x** [comment]
Fixed by uploading the head of `main` incorporating the latest PRs in a v1.1.0

**Comment by chr-1x** [comment]
I don't know what, if anything, was in v1.0b18, but it's gone now ¯\\\_(ツ)\_/¯
